AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cost-effective RDS PostgreSQL instance for Veritas Foundation'

Parameters:
  DatabasePassword:
    Type: String
    NoEcho: true
    Description: 'Password for the database master user'
    MinLength: 8
    MaxLength: 41
    ConstraintDescription: 'Must be between 8 and 41 characters'
  
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues: ['dev', 'staging', 'prod']
    Description: 'Environment name'

Resources:
  # Security Group for RDS
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Security group for Veritas Foundation RDS database'
      GroupName: !Sub 'veritas-db-sg-${Environment}'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0
          Description: 'PostgreSQL access'
      Tags:
        - Key: Name
          Value: !Sub 'veritas-db-sg-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  # DB Subnet Group (uses default VPC subnets)
  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: 'Subnet group for Veritas Foundation RDS'
      DBSubnetGroupName: !Sub 'veritas-db-subnet-group-${Environment}'
      SubnetIds:
        - !Ref DatabaseSubnet1
        - !Ref DatabaseSubnet2
      Tags:
        - Key: Name
          Value: !Sub 'veritas-db-subnet-group-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  # Subnets (using default VPC)
  DatabaseSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DefaultVPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: '172.31.64.0/20'
      Tags:
        - Key: Name
          Value: !Sub 'veritas-db-subnet-1-${Environment}'

  DatabaseSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DefaultVPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: '172.31.80.0/20'
      Tags:
        - Key: Name
          Value: !Sub 'veritas-db-subnet-2-${Environment}'

  # Default VPC reference
  DefaultVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '172.31.0.0/16'
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: 'Default VPC'

  # RDS Instance
  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub 'veritas-foundation-db-${Environment}'
      DBName: 'veritas_foundation'
      DBInstanceClass: 'db.t3.micro'
      Engine: 'postgres'
      EngineVersion: '15.4'
      MasterUsername: 'postgres'
      MasterUserPassword: !Ref DatabasePassword
      AllocatedStorage: '20'
      StorageType: 'gp2'
      StorageEncrypted: false
      MultiAZ: false
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      BackupRetentionPeriod: !If 
        - IsProduction
        - 7
        - 1
      PreferredBackupWindow: '03:00-04:00'
      PreferredMaintenanceWindow: 'sun:04:00-sun:05:00'
      AutoMinorVersionUpgrade: false
      Tags:
        - Key: Name
          Value: !Sub 'veritas-foundation-db-${Environment}'
        - Key: Environment
          Value: !Ref Environment

Conditions:
  IsProduction: !Equals [!Ref Environment, 'prod']

Outputs:
  DatabaseEndpoint:
    Description: 'RDS instance endpoint'
    Value: !GetAtt DatabaseInstance.Endpoint.Address
    Export:
      Name: !Sub '${AWS::StackName}-DatabaseEndpoint'
  
  DatabasePort:
    Description: 'RDS instance port'
    Value: !GetAtt DatabaseInstance.Endpoint.Port
    Export:
      Name: !Sub '${AWS::StackName}-DatabasePort'
  
  DatabaseName:
    Description: 'Database name'
    Value: 'veritas_foundation'
    Export:
      Name: !Sub '${AWS::StackName}-DatabaseName'
  
  EstimatedMonthlyCost:
    Description: 'Estimated monthly cost (USD)'
    Value: !If 
      - IsProduction
      - '$13-15 (after free tier)'
      - '$0 (free tier eligible)'
